Repository Bitbucket22/Bitbucket, pull requests merged in 2024-07, with the labels that each got.

#2 Feature/#1 user registration
  .gitignore
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/checksums/md5-checksums.bin
  .gradle/8.8/checksums/sha1-checksums.bin
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .idea/misc.xml
  build.gradle
  src/main/java/com/sparta/bitbucket/auth/config/PasswordConfig.java
  src/main/java/com/sparta/bitbucket/auth/controller/UserController.java
  src/main/java/com/sparta/bitbucket/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/bitbucket/auth/dto/SignupResponseDto.java
  src/main/java/com/sparta/bitbucket/auth/entity/Role.java
  src/main/java/com/sparta/bitbucket/auth/entity/User.java
  src/main/java/com/sparta/bitbucket/auth/repository/UserRepository.java
  src/main/java/com/sparta/bitbucket/auth/service/UserService.java
  src/main/resources/application.properties
Labels: feat

#11 Feature/#3 user auth
  build.gradle
  src/main/java/com/sparta/bitbucket/auth/controller/AuthController.java
  src/main/java/com/sparta/bitbucket/auth/controller/UserController.java
  src/main/java/com/sparta/bitbucket/auth/dto/LoginRequestDto.java
  src/main/java/com/sparta/bitbucket/auth/entity/Role.java
  src/main/java/com/sparta/bitbucket/auth/entity/User.java
  src/main/java/com/sparta/bitbucket/auth/service/AuthService.java
  src/main/java/com/sparta/bitbucket/auth/service/UserService.java
  src/main/java/com/sparta/bitbucket/common/config/JpaAuditingConfig.java
  src/main/java/com/sparta/bitbucket/common/dto/DataResponseDto.java
  src/main/java/com/sparta/bitbucket/common/dto/MessageResponseDto.java
  src/main/java/com/sparta/bitbucket/common/dto/NoContentResponseDto.java
  src/main/java/com/sparta/bitbucket/common/entity/Timestamped.java
  src/main/java/com/sparta/bitbucket/common/util/ResponseFactory.java
  src/main/java/com/sparta/bitbucket/security/JwtTokenProvider.java
  src/main/java/com/sparta/bitbucket/security/TokenType.java
  src/main/java/com/sparta/bitbucket/security/UserDetailsImpl.java
  src/main/java/com/sparta/bitbucket/security/config/JwtConfig.java
  src/main/java/com/sparta/bitbucket/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/bitbucket/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/bitbucket/security/service/JwtService.java
  src/main/java/com/sparta/bitbucket/security/service/UserDetailsServiceImpl.java
Labels: feat

#13 feature/#12-user-manager-role
  src/main/java/com/sparta/bitbucket/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/bitbucket/auth/dto/SignupResponseDto.java
  src/main/java/com/sparta/bitbucket/auth/entity/Role.java
  src/main/java/com/sparta/bitbucket/auth/entity/User.java
  src/main/java/com/sparta/bitbucket/auth/service/UserService.java
  src/main/java/com/sparta/bitbucket/common/util/ResponseFactory.java
Labels: feat

#14 Feat/#2 Make Frontend
  src/main/html/Login.html
  src/main/html/Main.html
  src/main/html/SignUp.html
  src/main/html/board.html
  src/main/html/create_board.html
Labels: feat

#16 Feat/#15 update html
  src/main/html/Main.html
  src/main/html/SignUp.html
  src/main/java/com/sparta/bitbucket/auth/service/AuthService.java
  src/main/java/com/sparta/bitbucket/auth/service/UserService.java
  src/main/java/com/sparta/bitbucket/common/controller/PageController.java
  src/main/java/com/sparta/bitbucket/common/dto/DataResponseDto.java
  src/main/java/com/sparta/bitbucket/common/dto/MessageResponseDto.java
  src/main/java/com/sparta/bitbucket/common/dto/NoContentResponseDto.java
  src/main/java/com/sparta/bitbucket/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/bitbucket/security/service/JwtService.java
  src/main/resources/templates/Login.html
  src/main/resources/templates/Main.html
  src/main/resources/templates/SignUp.html
Labels: feat

#19 Feat/#7 board
  src/main/java/com/sparta/bitbucket/board/controller/BoardController.java
  src/main/java/com/sparta/bitbucket/board/dto/BoardCreateRequestDto.java
  src/main/java/com/sparta/bitbucket/board/dto/BoardEditRequestDto.java
  src/main/java/com/sparta/bitbucket/board/dto/BoardInviteRequestDto.java
  src/main/java/com/sparta/bitbucket/board/dto/BoardMemberResponseDto.java
  src/main/java/com/sparta/bitbucket/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/bitbucket/board/dto/BoardWithMemberListResponseDto.java
  src/main/java/com/sparta/bitbucket/board/entity/Board.java
  src/main/java/com/sparta/bitbucket/board/entity/BoardMember.java
  src/main/java/com/sparta/bitbucket/board/repository/BoardMemberRepository.java
  src/main/java/com/sparta/bitbucket/board/repository/BoardRepository.java
  src/main/java/com/sparta/bitbucket/board/service/BoardService.java
  src/main/java/com/sparta/bitbucket/security/config/WebSecurityConfig.java
Labels: feat

#20 Feat/#5 column 기능 구현
  src/main/java/com/sparta/bitbucket/board/service/BoardService.java
  src/main/java/com/sparta/bitbucket/column/controller/ColumnController.java
  src/main/java/com/sparta/bitbucket/column/dto/ColumnRequestDto.java
  src/main/java/com/sparta/bitbucket/column/dto/ColumnResponseDto.java
  src/main/java/com/sparta/bitbucket/column/dto/CreateColumnRequestDto.java
  src/main/java/com/sparta/bitbucket/column/dto/EditColumnRequestDto.java
  src/main/java/com/sparta/bitbucket/column/entity/Columns.java
  src/main/java/com/sparta/bitbucket/column/entity/StatusMessage.java
  src/main/java/com/sparta/bitbucket/column/repository/ColumnRepository.java
  src/main/java/com/sparta/bitbucket/column/service/ColumnService.java
Labels: feat

#23 Feature/#18 exception handler 구현
  src/main/java/com/sparta/bitbucket/exception/GlobalExceptionHandler.java
Labels: feat

#24 Refactor/#17 service class updates and new custom exception
  src/main/java/com/sparta/bitbucket/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/bitbucket/auth/exception/PasswordInvalidException.java
  src/main/java/com/sparta/bitbucket/auth/exception/UsernameDuplicateException.java
  src/main/java/com/sparta/bitbucket/auth/service/AuthService.java
  src/main/java/com/sparta/bitbucket/auth/service/UserService.java
  src/main/java/com/sparta/bitbucket/column/controller/ColumnController.java
  src/main/java/com/sparta/bitbucket/column/entity/StatusMessage.java
  src/main/java/com/sparta/bitbucket/common/entity/StatusMessage.java
  src/main/java/com/sparta/bitbucket/common/util/ResponseFactory.java
  src/main/java/com/sparta/bitbucket/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/bitbucket/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/bitbucket/security/service/UserDetailsServiceImpl.java
Labels: refactor

#50 Feat/#31 comment 작성, 조회 프론트 연결
  src/main/java/com/sparta/bitbucket/comment/dto/CommentResponseDto.java
  src/main/resources/static/js/auth.js
  src/main/resources/static/js/board.js
  src/main/resources/static/js/card.js
  src/main/resources/static/js/comment.js
  src/main/resources/templates/board.html
Labels: feat

#51 Feat/#32 card to html
  src/main/java/com/sparta/bitbucket/card/entity/Card.java
  src/main/java/com/sparta/bitbucket/comment/service/CommentService.java
  src/main/resources/static/js/board.js
  src/main/resources/static/js/card.js
  src/main/resources/templates/board.html
Labels: feat

#52 refactor/#21 board Entity & board.html
  src/main/java/com/sparta/bitbucket/auth/AuthController.java
  src/main/java/com/sparta/bitbucket/auth/AuthService.java
  src/main/java/com/sparta/bitbucket/auth/UserController.java
  src/main/java/com/sparta/bitbucket/auth/UserRepository.java
  src/main/java/com/sparta/bitbucket/auth/UserService.java
  src/main/java/com/sparta/bitbucket/auth/entity/User.java
  src/main/java/com/sparta/bitbucket/board/BoardController.java
  src/main/java/com/sparta/bitbucket/board/BoardMemberRepository.java
  src/main/java/com/sparta/bitbucket/board/BoardRepository.java
  src/main/java/com/sparta/bitbucket/board/BoardService.java
  src/main/java/com/sparta/bitbucket/board/dto/BoardCreateRequestDto.java
  src/main/java/com/sparta/bitbucket/board/dto/BoardEditRequestDto.java
  src/main/java/com/sparta/bitbucket/board/dto/BoardRequestDto.java
  src/main/java/com/sparta/bitbucket/board/entity/Board.java
  src/main/java/com/sparta/bitbucket/card/CardController.java
  src/main/java/com/sparta/bitbucket/card/CardRepository.java
  src/main/java/com/sparta/bitbucket/card/CardService.java
  src/main/java/com/sparta/bitbucket/column/ColumnController.java
  src/main/java/com/sparta/bitbucket/column/ColumnRepository.java
  src/main/java/com/sparta/bitbucket/column/ColumnService.java
  src/main/java/com/sparta/bitbucket/comment/CommentController.java
  src/main/java/com/sparta/bitbucket/comment/CommentRepository.java
  src/main/java/com/sparta/bitbucket/comment/CommentService.java
  src/main/java/com/sparta/bitbucket/common/PageController.java
  src/main/java/com/sparta/bitbucket/common/entity/ErrorMessage.java
  src/main/java/com/sparta/bitbucket/exception/ErrorCode.java
  src/main/java/com/sparta/bitbucket/security/JwtService.java
  src/main/java/com/sparta/bitbucket/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/bitbucket/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/bitbucket/security/filter/JwtAuthorizationFilter.java
  src/main/resources/application.properties
  src/main/resources/static/js/auth.js
  src/main/resources/static/js/board.js
  src/main/resources/templates/board.html
Labels: fix, refactor

#54 [refactor] Coding Conventions
  src/main/java/com/sparta/bitbucket/auth/dto/BoardSummaryDto.java
  src/main/java/com/sparta/bitbucket/auth/dto/SignupResponseDto.java
  src/main/java/com/sparta/bitbucket/auth/dto/UserBoardsResponseDto.java
  src/main/java/com/sparta/bitbucket/board/BoardService.java
  src/main/java/com/sparta/bitbucket/board/dto/BoardMemberResponseDto.java
  src/main/java/com/sparta/bitbucket/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/bitbucket/column/dto/ColumnRequestDto.java
  src/main/java/com/sparta/bitbucket/common/dto/NoContentResponseDto.java
  src/main/java/com/sparta/bitbucket/common/util/ResponseFactory.java
  src/main/java/com/sparta/bitbucket/security/config/JwtConfig.java
Labels: refactor
